
name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Defaults to patch version, will bump minor on "feat" commit

      - name: Get Next Version
        id: semver
        continue-on-error: true
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          patchAll: true
          fallbackTag: "0.1.0"

      - name: Check for Version Bump
        id: check_version
        run: |
          if [ -z "${{ steps.semver.outputs.next }}" ]; then
            echo "No version bump detected. Skipping workflow."
            exit 0
          fi

      - name: Push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.semver.outputs.next }}
          tag_prefix: ""

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jaysuzi5/weather-collector:latest
            ghcr.io/jaysuzi5/weather-collector:${{ steps.semver.outputs.next }}
